fix bashizm

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3,7 +3,8 @@
 #  https://github.com/Rblp/Rblpapi/blob/master/configure
 
 ## Check that we are on Unix
-if ! [ -x $(command -pv uname) ]; then
+which uname
+if [ $? -ne 0 ]; then
     echo "You do not have 'uname' so this is unlikely to be a Unix system. Exiting."
     exit 1
 fi
@@ -13,8 +14,6 @@ PKG_TEST_HEADER="<kiwi/Kiwi.h>"
 PKG_LIBS="-lkiwi"
 PKG_CPPFLAGS=""
 LIB_VER="0.11.1"
-
-git config --global advice.detachedHead false
 
 # Copy libcache for local development.
 if [ -f "`pwd`/kiwilibtmp/libs/libkiwi.a" ]; then
@@ -38,7 +37,23 @@ else
   echo "Prior system libkiwi installation not found"
   echo "Preparing to download and build library from source..."
 
-  if ! [ -x $(command -pv cmake) ]; then
+  which git
+  if [ $? -ne 0 ]; then
+    echo "------------------------------[ ELBIRD ]------------------------------"
+    echo "Configuration failed because 'git' was not found."
+    echo "If you want to kiwi build from source in package installation prosess,"
+    echo "make sure git and cmake work in system."
+    echo "-------------------------------------------------------------------------"
+    exit 1
+  fi
+
+  which cmake
+  if [ $? -ne 0 ]; then
+    export PATH=$PATH:/Applications/CMake.app/Contents/bin
+  fi
+
+  which cmake
+  if [ $? -ne 0 ]; then
     echo "------------------------------[ ELBIRD ]------------------------------"
     echo "Configuration failed because 'libkiwi' and 'cmake' were not found."
     echo "If 'libkiwi' is already installed but in a non-standard location, you"
@@ -51,6 +66,7 @@ else
     exit 1
   fi
 
+  git config --global advice.detachedHead false
   git clone --depth 1 https://github.com/bab2min/Kiwi
   cd Kiwi
   git rm third_party/googletest
@@ -58,10 +74,6 @@ else
   git submodule update --init --recursive
   mkdir build
   cd build
-  which cmake
-  if [ $? -ne 0 ]; then
-    export PATH=$PATH:/Applications/CMake.app/Contents/bin
-  fi
   cmake -DCMAKE_BUILD_TYPE=Release -DKIWI_BUILD_TEST=OFF -DKIWI_USE_CPUINFO=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON --log-level=ERROR ..
   echo "** make is running..."
   make kiwi_static 1> makelog.txt
